In [1]:
import numpy as np
arr = np.array([2,4,6,8])
print("Array:",arr)

Array: [2 4 6 8]


In [2]:
print("Shape(dimensions):",arr.shape)
print("Data Type of elemnets:",arr.dtype)
print("Size(total number of elements):",arr.size)
print("NUmber of dimensions:",arr.ndim)

Shape(dimensions): (4,)
Data Type of elemnets: int64
Size(total number of elements): 4
NUmber of dimensions: 1


In [4]:
zero_array = np.zeros((3,3))
print("Zero Array: \n", zero_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones_array = np.ones((2,4))
print("Ones Array: \n", ones_array)

Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
random_array = np.random.random((3,3))
print("Random Array: \n", random_array)

Random Array: 
 [[0.49063591 0.03615246 0.09636761]
 [0.85538105 0.25609079 0.97368504]
 [0.93294384 0.01894721 0.77145817]]


In [7]:
identity_matrix = np.eye(4)
print("Identity Matrix: \n", identity_matrix)

Identity Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print("Number of dimensions:",arr.ndim)

Number of dimensions: 2


In [10]:
arr = np.array([3,4,5], dtype=np.int32)
print("Byte size of element:",arr.itemsize)

Byte size of element: 4


In [11]:
arr = np.array([1.5,2.5,3.8])
print("data type of elements:",arr.dtype)

data type of elements: float64


In [15]:
arr = np.array([11,22,33,44,55])
print("Sliced Array:\n",arr[1:3])

Sliced Array:
 [22 33]


In [16]:
arr = np.linspace(1,10,5)
print("Evenly Spaced array:\n",arr)

Evenly Spaced array:
 [ 1.    3.25  5.5   7.75 10.  ]


In [17]:
arr = np.array([25,36,81])
print("Max:",arr.max())
print("Min:",arr.min())
print("Sum:",arr.sum())
print("Square root:",np.sqrt(arr))

Max: 81
Min: 25
Sum: 142
Square root: [5. 6. 9.]


In [18]:
arr = np.array([[1,2,3],[4,5,6]])
print("Flattened array: ",arr.ravel())

Flattened array:  [1 2 3 4 5 6]


In [19]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Concatenated array:",np.concatenate((arr1,arr2)))

Concatenated array: [1 2 3 4 5 6]


In [20]:
stacked_array = np.stack((arr1,arr2),axis=1)
print("Stacked array:\n",stacked_array)

Stacked array:
 [[1 4]
 [2 5]
 [3 6]]


In [21]:
stack_array = np.hstack((arr1,arr2))
print("Horizontal Stacked array:",stack_array)

Horizontal Stacked array: [1 2 3 4 5 6]


In [22]:
stack_array = np.vstack((arr1,arr2))
print("Vertical Stacked array:\n",stack_array)

Vertical Stacked array:
 [[1 2 3]
 [4 5 6]]


In [23]:
arr = np.array([1,2,3,4,5,6])
print("Splitted array:\n",np.array_split(arr,3))

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
arr = np.array([10,20,30,40,50])
indices = np.where(arr == 30)
print("Index of 30P:",indices)

Index of 30P: (array([2]),)


In [25]:
arr = np.array([3,4,6,7])
sorted_array = np.sort(arr)
print("Sorted array:",sorted_array)

Sorted array: [3 4 6 7]


In [26]:
arr = np.array([10,20,30,40])
print("Element at index 2:",arr[2])

Element at index 2: 30


In [27]:
print("Slice[1:3]",arr[1:3])

Slice[1:3] [20 30]


In [29]:
for x in arr:
    print("Element:",x)

Element: 10
Element: 20
Element: 30
Element: 40


In [32]:
original = np.array([1,2,3,4])
copied = original.copy()
copied[0] = 100
print("Original:",original)
print("Copied array:",copied)

Original: [1 2 3 4]
Copied array: [100   2   3   4]


In [31]:
arr = np.array([1,2,3,4,5,6])
reshaped_array = arr.reshape(2,3)
print("Reshaped array:\n",reshaped_array)

Reshaped array:
 [[1 2 3]
 [4 5 6]]
