In [12]:
import numpy as np

In [13]:
arr = np.random.rand(5,5)

In [14]:
arr

array([[0.06083991, 0.9863704 , 0.7238413 , 0.80779173, 0.80859051],
       [0.25920939, 0.00313495, 0.35331725, 0.30586298, 0.94711793],
       [0.27162212, 0.73397283, 0.69628622, 0.6663517 , 0.5386324 ],
       [0.75902329, 0.59617735, 0.15336225, 0.12275443, 0.27665806],
       [0.99403691, 0.63195094, 0.96252226, 0.02064015, 0.36887806]])

In [15]:
arr.shape

(5, 5)

In [16]:
arr.dtype

dtype('float64')

In [17]:
arr[:4]

array([[0.06083991, 0.9863704 , 0.7238413 , 0.80779173, 0.80859051],
       [0.25920939, 0.00313495, 0.35331725, 0.30586298, 0.94711793],
       [0.27162212, 0.73397283, 0.69628622, 0.6663517 , 0.5386324 ],
       [0.75902329, 0.59617735, 0.15336225, 0.12275443, 0.27665806]])

In [18]:
arr[4]

array([0.99403691, 0.63195094, 0.96252226, 0.02064015, 0.36887806])

In [19]:
arr[:4].shape

(4, 5)

In [20]:
arr[:, :4]

array([[0.06083991, 0.9863704 , 0.7238413 , 0.80779173],
       [0.25920939, 0.00313495, 0.35331725, 0.30586298],
       [0.27162212, 0.73397283, 0.69628622, 0.6663517 ],
       [0.75902329, 0.59617735, 0.15336225, 0.12275443],
       [0.99403691, 0.63195094, 0.96252226, 0.02064015]])

In [21]:
arr[1,1]

0.003134954171479687

In [22]:
arr[:-1]

array([[0.06083991, 0.9863704 , 0.7238413 , 0.80779173, 0.80859051],
       [0.25920939, 0.00313495, 0.35331725, 0.30586298, 0.94711793],
       [0.27162212, 0.73397283, 0.69628622, 0.6663517 , 0.5386324 ],
       [0.75902329, 0.59617735, 0.15336225, 0.12275443, 0.27665806]])

In [23]:
int_arr = np.random.randint(5,size = (6,8))

In [24]:
int_arr_0 = int_arr[0]

In [25]:
int_arr_0

array([3, 0, 2, 2, 1, 3, 3, 3])

In [26]:
int_arr_0 == 0

array([False,  True, False, False, False, False, False, False])

In [28]:
int_arr_0 == 2

array([False, False,  True,  True, False, False, False, False])