In [1]:
import numpy as np

In [2]:
python_list = [1,2,3,4,5]

In [3]:
python_list

[1, 2, 3, 4, 5]

In [4]:
np.array(python_list)

array([1, 2, 3, 4, 5])

In [5]:
numpy_arr = np.array(python_list)

In [6]:
numpy_arr.shape

(5,)

In [7]:
len(numpy_arr.shape)

1

In [8]:
python_list_list = [[1,2],[3,0]]

In [9]:
python_list_list

[[1, 2], [3, 0]]

In [10]:
np.array(python_list_list)

array([[1, 2],
       [3, 0]])

In [12]:
numpy_arr2 = np.array(python_list_list)

In [13]:
len(numpy_arr2.shape)

2

In [14]:
numpy_arr2.shape

(2, 2)

In [15]:
numpy_arr2

array([[1, 2],
       [3, 0]])

In [17]:
python_list_list = [[1,2,5],[3,0,9]]

In [18]:
np.array(python_list_list).shape

(2, 3)

In [19]:
list(range(5))

[0, 1, 2, 3, 4]

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
np.ones((1,1))

array([[1.]])

In [25]:
np.random.randint(5)

4

In [26]:
np.random.randint(5, size=(2,2))

array([[3, 4],
       [4, 0]], dtype=int32)