In [1]:
import numpy as np

In [2]:
marks = [[1,2,3,4],[5,6,7,8],[9,0,1,2]]

In [3]:
marks[0]

[1, 2, 3, 4]

In [5]:
marks[0][0],marks[1][0],marks[2][0]

(1, 5, 9)

In [7]:
marks_transpose = []
for j in range(len(marks[0])):
    marks_transpose.append([])
    for i in range(len(marks)):
        marks_transpose[j].append(marks[i][j])

In [8]:
marks_transpose

[[1, 5, 9], [2, 6, 0], [3, 7, 1], [4, 8, 2]]

In [9]:
mark_array = np.array(marks)

In [11]:
mark_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [12]:
mark_array.T

array([[1, 5, 9],
       [2, 6, 0],
       [3, 7, 1],
       [4, 8, 2]])

In [13]:
mark_array.sum(axis = 1)

array([10, 26, 12])

In [14]:
mark_array.sum(axis = 1)/60

array([0.16666667, 0.43333333, 0.2       ])

In [15]:
mark_array.T.sum(axis = 1)

array([15,  8, 11, 14])